### ISSUE TITLE
Getting no podfile found after pod install

### ISSUE THREAD

**Issue by aviadavi** [adaptant-labs/flutter_windowmanager#3]
Hi,

I'm getting an error while trying to pod install:

No podspec found for "flutter_windowmanager" in .symlinks/plugins/flutter_windowmanager/ios
Any idea?

Thanks,
Aviad A

**Comment by pmundt** [comment]
The plugin itself will not work on iOS, as it wraps to an underlying Android service. There's another module you could look at for iOS, which I've since updated the README for. Unfortunately, there doesn't seem to be a way to flag this as Android-only in pub.dev, there's an issue open about this in https://github.com/flutter/flutter/issues/10530.
