### ISSUE TITLE
not even blocking screenshot

### ISSUE THREAD

**Issue by Atominac** [adaptant-labs/flutter_windowmanager#7]

**Comment by pmundt** [comment]
The FLAG_SECURE behaviour is unfortunately not always consistent, on some it blacks out the application window entirely, while on others it just applies a kind of watermark, but still leaves the screen very much readable. You haven't exactly provided any information about what you are doing, on which version, etc. so it's rather difficult to give much in the way of suggestions of what to look at.

If the issue is persisting, please re-open the issue with more detailed information about your environment.
